name: User Engagement Analysis CI

on:
  push:
    branches:
     - task-2
    paths:
      - '**.py'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run unit tests
      - name: Run unit tests
        run: |
          python -m unittest discover tests/

      # (Optional) Run code quality checks
      - name: Run Flake8 linter
        run: |
          pip install flake8
          flake8 .
